### ISSUE TITLE
pds4_create_xml_index should print a message when no index file is generated

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/rms-pds4indextools#17]
pds4_create_xml_index.py:

During the meeting today, we discuss that when `--output-headers-file` is provided but `--output-index-file` is not, the behavior is to not output an index file. However, @matthewtiscareno also suggested printing an explicit message saying that an index file is not being generated to make sure there is no user confusion. Such a message would say something like:

```
No index file generated because --output-headers-file was provided without --output-index-file
```

**Comment by matthewtiscareno** [comment]
By the same token, there should always be something like the following when an index file is written, even in non-verbose mode:
`Wrote index file:  path/filename`

**Comment by rfrenchseti** [comment]
> By the same token, the tool should always print something like the following when an index file is written, even in non-verbose mode: `Wrote index file: path/filename`

This was already done in the final version tonight.
