### ISSUE TITLE
Consider other ways of adding extra file info

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/rms-pds4indextools#35]
pds4_create_xml_index:

From Slack:

- The `--limit-xpaths` file doesn't include the `--extra-file-info` columns, making it impossible to completely order the resulting columns.
- We could address this issue by approaching the extra file info in a totally different way than we currently do. What if we always turned on all of the possible extra file info columns? And then included them in the dumped headers file, and made them handled by the limit file? So by default if you specified nothing, you would get an index file with all the label columns, plus lid, bundle name, file, filepath, etc. And if you didn't want those new columns, you could delete them by using the --limit-xpaths option.
- Alternatively, you could keep those extra columns as options on the command line, but still allow them to be filtered (and ordered) by --limit-xpaths. This would also get the job done, although with the added confusion that if you have one of those columns listed in the --limit-xpaths file and forget to turn it on as a command line option, it won't show up.

**Comment by esimpsons3ti** [comment]
This was addressed by the code overhaul, and is now fixed.
